name: dinbog
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  get_it: ^4.0.4
  injectable: ^1.0.4
  flushbar: ^1.10.4
  uuid: ^2.2.0
  auto_route: ^0.5.0
  kt_dart: ^0.7.0+1
  json_annotation: ^3.0.1
  rxdart: ^0.24.1
  flutter_hooks: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.11.6
  lint: ^1.2.0
  injectable_generator: ^1.0.4
  auto_route_generator: ^0.5.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
