name: dinbog
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.7.1
  flutter_bloc: ^6.0.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.9.2

flutter:
  uses-material-design: true
