name: dinbog
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  get_it: ^4.0.4
  injectable: ^1.0.4
  flushbar: ^1.10.4
  uuid: ^2.2.0
  auto_route: ^0.6.7
  kt_dart: ^0.7.0+1
  json_annotation: ^3.0.1
  rxdart: ^0.24.1
  flutter_hooks: ^0.13.0
  flutter_svg: ^0.18.1
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.11.6
  lint: ^1.2.0
  injectable_generator: ^1.0.4
  auto_route_generator: ^0.6.8
  json_serializable: ^3.3.0
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo_alpha.png"
  adaptive_icon_background: "assets/img/logo_alpha.png"

flutter:
  uses-material-design: true
  #assets:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
# flutter_intl:
#   enabled: false
#   main_locale: en
#   class_name: S
# dependency_overrides:
#   analyzer: "0.39.14"

